fix(tests): Fix unused variable errors in snapshot_tests.rs
Move variables inside #[cfg(unix)] block where they are actually used:
- snapshot_dir: Only used in unix-specific symlink test
- manager: Only used to call restore_snapshot in unix block
- malicious_archive: Only used in unix symlink creation

This fixes compilation errors on Ubuntu CI:
- error[E0425]: cannot find value 'malicious_archive' in this scope
- error[E0425]: cannot find value 'manager' in this scope

Variables were previously prefixed with _ (unused) but are actually
used inside #[cfg(unix)] conditional compilation block.